### ISSUE TITLE
Commas with children in Czech UD1.2

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/UD_Czech#2]
http://hdl.handle.net/11346/PMLTQ-9FRQ
`a-node [form = ',', a-node []]`

This query finds three sentences, where a number with a decimal comma is completely broken.
This test (punctuation should have no children) could be applied also to other treebanks (and included in the regular UD tests).

**Comment by dan-zeman** [comment]
Thanks for reporting. All three are actually errors in PDT 3.0, see here:
http://hdl.handle.net/11346/PMLTQ-JFM4
I will look into it and fix it during conversion.
