### ISSUE TITLE
Copula with modal verbs

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/UD_Czech#3]
```
# sent_id = cmpr9406-001-p3s1B
# text = Pomocí může být systém ECM
# gloss = Help can be system ECM
─┮
 │ ╭────────────────┮ Pomocí NOUN xcomp
 ╰─┾ může VERB root │
   │                ╰─╼ být AUX cop
   ╰─┮ systém NOUN nsubj
     ╰─╼ ECM NOUN nmod
```

Copula verb "být" is clearly related to the modal "může", in PDT style, one should depend on the other. In English UD "can be" is annotated as siblings.
I know the UD guidelines about copulas (although I don't like them) and the discussion about which verbs are considered modal/auxiliary in which language, but I still wonder if this is the correct analysis.

**Comment by dan-zeman** [comment]
Yes, it is correct. There is an infinitival clause (consisting of a copula and a non-verbal predicate) _být pomocí_ “to be help(ful)”. The copula is an auxiliary finite verb, which supplies the feature `VerbForm=Inf` that cannot be morphologically expressed directly by the non-verbal predicate. But UD treats them as if they were one unit.
