### ISSUE TITLE
Training data isn't merged

### ISSUE THREAD

**Issue by kylebgorman** [UniversalDependencies/UD_Czech#4]
The docs here say that training data that was once separated by subgenre has been merged into a single file `cs_pdt-ud-train.conllu`, but this file isn't present in the repo. Either docs should be updated or the 4 training files should be concatenated and uploaded. (I'd be willing to do either myself but my employers forbids me to to contribute to non-commercial-licensed projects.)

**Comment by dan-zeman** [comment]
The documentation pertains to the officially released package (see http://universaldependencies.org/#download), not to the contents of the repo.

In fact you cannot do this in the repo even if your employer allows you to do it because Github will not allow it.
