### ISSUE TITLE
Segmentation

### ISSUE THREAD

**Issue by robvanderg** [UniversalDependencies/UD_Czech#7]
There are many cases like this:

Ministerstvo financí ČR zatím schválilo prodejní cenu; rozhodlo tak ve smyslu
platných cenových předpisů, jež neurčují jiné právní vztahy." Souhlasem jsme
nepředurčili, komu mají pozemky připadnout," konstatuje ing. P. Slaný, ředitel
 
Where the second sentence is supposed to start with " Souhlasem jsme
Is the space in the original data really after the "?, or should it be before?

**Comment by dan-zeman** [comment]
It should be before but it was after the quote in the original data.

UD_Czech-PDT is converted from the Prague Dependency Treebank 3.5, which preserves the original text, as received from the publisher, including editing errors such as this one. This particular sentence can be seen [here](http://hdl.handle.net/11346/PMLTQ-XOMD).
